language: node_js

node_js:
  - node
  - 10

git:
  depth: 3

cache:
  yarn: true
  directories:
    - .npm

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --ignore-scripts --ignore-engines

script:
  - yarn run lint
  - yarn run build
  - yarn run test-coverage
